version: '3.9'
services:
  cms:
    build: ../cms
    env_file: .env
    ports:
      - "1337:1337"
    volumes:
      - ../cms:/app
  orchestrator:
    image: n8nio/n8n
    env_file: .env
    ports:
      - "5678:5678"
    volumes:
      - ../orchestrator:/home/node/.n8n
  frontend:
    build: ../frontend
    env_file: .env
    ports:
      - "3000:3000"
    command: "npm run start"
    volumes:
      - ../frontend:/app
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
